name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: dsanchor
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'microsoft'

      - name: Build JAR
        run: mvn package -DskipTests

      - name: Build Docker image
        run: |
          docker build \
            --tag ghcr.io/${{ github.repository }}/demo-app:latest \
            .

      - name: Login to GitHub Packages
        run: |
          echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin

      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository }}/demo-app:latest